<?php require_once __DIR__ . '/../../../base.phtml'; ?>
<?php require_once __DIR__ . '/../coreNavLesson.phtml'; ?>

<body>

    <section class="lesson-content"> <!-- Lesson Content Start -->
        <div class="lesson-container"> <!-- Lesson Container Start -->
            <div class="content"> <!-- Content Start -->
                <h1>Chapter 1.7 - Keywords and Naming Identifiers</h1>
                <hr>
                <div class="part-content">
                    <p>
                        All languages have set words for its own use. These words are called keywords, and each of these keywords have a special meaning 
                        to the language. Each are specific to their own language.
                    </p>
                </div>

                <div class="part-content">
                    <h2>Naming Rules</h2>
                    <p>
                        As a reminder the name of a variable, function, or type is called an identifier. Some languages may offer flexibility to 
                        the name identifiers as you wish. However, there are a few rules that must be followed when naming identifiers.
                    </p>
                    <p>
                        <ul>
                            <li>The identifier cannot be a keyword. Keywords are reserved.</li>
                            <li>
                                The identifier can only be composed of letters (lowercase or uppercase), numbers and the underscore character. That means the name 
                                cannot contain symbols (except underscore) nor whitespaces,
                            </li>
                            <li>The identifier must begin with a letter or an underscore. It cannot start with a number.</li>
                            <li>Your program seems like j working but produces incorrect results later in the program. </li>
                            <li>
                                Most identifiers are case sensitive, and thus distinguishes between lower- and upper-case letters, 
                                nvalue is different than nValue is different than NVALUE.
                            </li>
                        </ul> 
                    </p>
                </div>
            
                <div class="prev-next">
                    <div class="prev-next-inline">
                        <a class="nav-link" href="1_8.php">
                            <div class="nav-button nav-button-next">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Next Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.8</span>
                                        Whitespace and Basic Formatting
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="../coreChapter.php">
                            <div class="nav-button nav-button-index">
                                <div class="nav-button-icon">
                                    <i class="fas fa-home" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Back to Table of Contents</div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="1_6.php">
                            <div class="nav-button nav-button-prev">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Previous Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.6</span>
                                        Data Types
                                    </div>
                                </div>
                            </div>
                        </a>

                    </div>
                </div>
            </div> <!-- Content End -->
        </div> <!-- Lesson Container End -->
    </section> <!-- Lesson Content End -->
    
<script src="/../js/quiz.js"></script>

</body>

<?php require_once __DIR__ . '/../../footer.phtml'; ?>
