<?php require_once __DIR__ . '/../../../base.phtml'; ?>
<?php require_once __DIR__ . '/../coreNavLesson.phtml'; ?>

<body>

    <section class="lesson-content"> <!-- Lesson Content Start -->
        <div class="lesson-container"> <!-- Lesson Container Start -->
            <div class="content"> <!-- Content Start -->
                <h1>Chapter 1.13 - If Statements</h1>
                <hr>
                <div class="part-content">
                    <p>
                        Consider a case where you are going to go to the market, and your roommate tells you, “if they have strawberries 
                        on sale, buy some”. This is a conditional statement, meaning that you will execute some action (“buy some”) only 
                        if the condition (“they have strawberries on sale”) is true.
                    </p>
                    <p>
                        Such conditions are common in programming, as they allow us to implement conditional behaviour into our programs. 
                        The simplest kind of conditional statement in programming languages is called an if statement. An if statement 
                        allows us to execute one (or more) lines of code only is some condition is met.
                    </p>
                    <p>
                        The simplest if statement takes the following form: <br>
                        <i>if (condition) true_statement;</i>
                    </p>
                    <p>
                        For readability, this is more often written as following:<br>
                        <i>If (condition)<br>
                        true_statement</i>
                    </p>
                    <p>
                        a condition (also called a conditional expression) is an expression that evaluates to a Boolean value. 
                        If the condition of an if statement evaluates to Boolean value true, then true_statement is executed. If 
                        the condition instead evaluates to Boolean value false, then true_statement is skipped.
                    </p>
                </div>

                <div class="part-content">
                    <h2>Using an IF Statement</h2>
                    
                    <p>
                        First, the user enters an integer. Then the condition x == 0 is evaluated. The equality operator(==) is 
                        used to test whether two values are equal. Operator== returns true if the operands are equal, and false 
                        if they are not. Once inputting x as 0, and 0==0 is true, this expression will be true.
                    </p>
                    <p>
                        If you were to input any number other than “0”. The subsequent statement is skipped, in this case the program ends and nothing else is printed.
                    </p>
                    <img src="../../img/core/Chapter1/picture6.png" class="chap-1_1-picture6">
                    <div class="lesson-warning">
                        <p>
                            <mark>Warning</mark> – if statements only conditionally execute a single statement. We talk about how to 
                            conditionally execute multiple statements in a later lesson.
                        </p>
                    </div>

                </div>
                
                

                <div class="prev-next">
                    <div class="prev-next-inline">
                        <a class="nav-link" href="1_14.php">
                            <div class="nav-button nav-button-next">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Next Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.14</span>
                                        Why Functions are Useful
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="../coreChapter.php">
                            <div class="nav-button nav-button-index">
                                <div class="nav-button-icon">
                                    <i class="fas fa-home" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Back to Table of Contents</div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="1_12.php">
                            <div class="nav-button nav-button-prev">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Previous Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.12</span>
                                        Boolean
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
        
            </div> <!-- Content End -->
        </div> <!-- Lesson Container End-->
    </section> <!-- Lesson Content End -->
        
<script src="/../js/quiz.js"></script>

</body>

<?php require_once __DIR__ . '/../../footer.phtml'; ?>
