<?php require_once __DIR__ . '/../../../base.phtml'; ?>
<?php require_once __DIR__ . '/../coreNavLesson.phtml'; ?>

<body>

    <section class="lesson-content"> <!-- Lesson Content Start -->
        <div class="lesson-container">  <!-- Lesson Container Start -->
            <div class="content">  <!-- Content Start -->
                <h1>Chapter 1.3 - Objects and Variables</h1>
                <hr>
                <div class="part-content">
                    <h2>Data</h2>
                    <p>
                        Most instructions in a program are statements, and the statements are grouped into functions which will then (hopefully) 
                        perform actions that the program was designed to produce.
                    </p>
                    <p>
                        How do programs produce these results? They do so by manipulating (reading, changing, and writing) data.
                        In computing, data is any information that can be moved, processed, or stored by a computer.
                    </p>
                    <h2>Objects and Variables</h2>
                    <p>
                        Every computer has memory, this is called <b>RAM</b> (Random Access Memory). You can think of RAM as a series of numbered 
                        mailboxes that can each be used to hold a piece of data while the program is running. A single piece of data, 
                        stored in memory somewhere, is called a <b>value</b>.
                    </p>
                    <p>
                        Some languages do not allow memory access. Instead, we use an indirect method through objects. An <b>object</b> is a region of storage 
                        (usually memory) that has a value and other associated properties. How the compiler and operating system work to assign memory 
                        to objects will later be discussed. But the key point here is that rather than say “go get the value stored in mailbox 1242”, 
                        we can say “get the value stored by this object”. This means we can focus on using objects to store and retrieve values, and not 
                        have to worry about where in memory they are being placed.
                    </p>
                    <p>
                        Objects can be named and unnamed. A named object is called a variable, and the name of the object is called an identifier. 
                        In our programs, most of the objects we create, and use will be variables.
                    </p>
                </div>

                <div class="part-content quiz">

                    <h2>Chapter 1.1 End of Topic Quiz</h2>
                    <p>
                        The following quiz is meant to reinforce your understanding of the material presented above.
                    </p>
<!-- --------------------------------------------------Question 1 Start --------------------------------------------------------------------------------- -->
                    <h3 class="quiz-question">1. What is data?</h3>
                    <button onclick="show_hide(this)" class="quiz-button">Show Solution</button>
                    <p id="answer">
                        <b>Data</b> is any information that can be moved, processed, or stored by a computer.
                    </p>
                    <br><br><hr>

<!-- ------------------------------------------------Question 2 Start --------------------------------------------------------------------------------- -->
                    <h3 class="quiz-question">2. What is a Value? </h3>
                    <button onclick="show_hide(this)" class="quiz-button">Show Solution</button>
                    <p id="answer">
                        A <b>value</b> is a single piece of data stored in memory.
                    </p>
                    <br><br><hr>

<!-- ----------------------------------------------- Question 3 Start --------------------------------------------------------------------------------- -->
                    <h3 class="quiz-question">3. What is a variable</h3>
                    <button onclick="show_hide(this)" class="quiz-button">Show Solution</button>
                    <p id="answer">
                        A <b>variable</b> is a named region of memory.
                    </p>
                    <br><br><hr>
<!-- ----------------------------------------------- Question 4 Start --------------------------------------------------------------------------------- -->
                        <h3 class="quiz-question">4. What is an identifier</h3>
                        <button onclick="show_hide(this)" class="quiz-button">Show Solution</button>
                        <p id="answer">
                        An <b>identifier</b> is the name that a variable is accessed by.
                        </p>
                        <br><br><hr>
                </div>

                <div class="prev-next">
                    <div class="prev-next-inline">
                        <a class="nav-link" href="1_4.php">
                            <div class="nav-button nav-button-next">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Next Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.4</span>
                                        Variable Assignment and Initialization
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="../coreChapter.php">
                            <div class="nav-button nav-button-index">
                                <div class="nav-button-icon">
                                    <i class="fas fa-home" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Back to Table of Contents</div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="1_2.php">
                            <div class="nav-button nav-button-prev">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Previous Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.2</span>
                                        Comments
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

            </div> <!-- Content End -->
        </div> <!-- Lesson Container End -->
    </section><!-- Lesson Content End -->
    
<script src="/../js/quiz.js"></script>

</body>

<?php require_once __DIR__ . '/../../footer.phtml'; ?>
