<?php require_once __DIR__ . '/../../../base.phtml'; ?>
<?php require_once __DIR__ . '/../coreNavLesson.phtml'; ?>

<body>

    <section class="lesson-content"> <!-- Lesson Content Start -->
        <div class="lesson-container"> <!-- Lesson Container Start -->
            <div class="content"> <!-- Content Start -->
                <h1>Chapter 1.9 - Introduction to Literals and Operators</h1>
                <hr>
                <div class="part-content">
                    <h2>Literals</h2>
                    <p>
                        Consider the following statements:
                    </p>
                        <pre>
                            <code class="language-cpp line-numbers">
                                std::cout << "Hello World!";
                                int x { 5 };
                            </code>
                        </pre>
                    <p>
                        The above statements are literals. A literal is a fixed value that has been directly inserted into the source code. Literals and 
                        variables both have a value and type. However, the value of a literal is fixed and cannot be changed, whereas the value of a 
                        variable can be changed through initialization and assignment.
                    </p>
                </div>

                <div class="part-content">
                    <h2>Operators</h2>
                    <p>
                        In mathematics, an operation is a mathematical calculation involving zero or more input values (called operands) 
                        that produces a new output value. The specific operation to be performed is denoted by a construct (typically a 
                        symbol or pair of symbols) called an operator. 
                    </p>
                    <p>
                        You are likely familiar with standard arithmetic operators from common usage in mathematics, including addition, subtraction, 
                        multiplication, and division. Assignment (=) is an operator as well as insertion and extraction (<<,>>). Some operators 
                        use more than one symbol, such as the equality operator (==), which allows us to compare two values to see if they are equal. 
                        There are also several operators that are words (new, delete, throw).
                    </p>
                    <p>
                        The number of operands than an operator takes as input is called the operators arity. Operators in C++ have three different arities:
                    </p>
                    <p>
                        <b>Unary</b> - These operators act on one operand. <br>
                        <b>Binary</b> - These operators act on two operands known as left and right.<br>
                        <b>Ternary</b> - These operators act on three operands.
                    </p>
                </div>
                
                <div class="prev-next">
                    <div class="prev-next-inline">
                        <a class="nav-link" href="1_10.php">
                            <div class="nav-button nav-button-next">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Next Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.10</span>
                                        Expressions
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="../coreChapter.php">
                            <div class="nav-button nav-button-index">
                                <div class="nav-button-icon">
                                    <i class="fas fa-home" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Back to Table of Contents</div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="1_8.php">
                            <div class="nav-button nav-button-prev">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Previous Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.8</span>
                                        Whitespace and Basic Formatting
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
        
            </div> <!-- Content End -->
        </div> <!-- Lesson Container End -->
    </section> <!-- Lesson Content End -->

<script src="/../js/quiz.js"></script>

</body>

<?php require_once __DIR__ . '/../../footer.phtml'; ?>
