<?php require_once __DIR__ . '/../base.phtml';?>
<?php require_once __DIR__ . '/nav.phtml';?>
<body>
<!--------------------------------------- Head Section -------------------------------------->
    <div class="text-box">
        <h1>Choose Your Langauge</h1>
        <p>
            Learning a Programming Langauge is easy when you get taught the correct way!<br>
            Begin now and start your path to a new career!
        </p> 
        
    </div>
    </section>
    
<!--------------------------------------- Course Section -------------------------------------->
    <section class="course">
        
        <h2>Courses We Offer</h2>
        <i class="fas fa-exclamation-triangle"></i> From here mobile users will not be able to view certain parts of these tutorials
        <p>
            Welcome to CodeMadeEasy Programming tutorials! Above all else, these tutorials aim to make programming easy unlike many other sites and books. 
            These tutorials assume that you have no prior knowledge of programming. We will teach you everything you need to know as you progress, 
            with lots of examples on the way!
        </p>

        <div class="row2">
                <div class="course-col">
                    <h3>Core Programming Concepts</h3>
                    <p>
                        This course will teach you the basic programming concepts for you to begin your journey with programming, the course involves
                        many interactive quizes and great content to help your learning experience.<br><br>
                        <a href="core/coreChapter.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
                <div class="course-col">
                    <h3>C++</h3>
                    <p>
                        C++ is the extended version of the C Language. This object-oriented language offers a clearer understanding of Various
                        programs and helps develop high-performance applications that can be used on multiple platforms.<br><br>
                        <a href="unavailable.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
                <div class="course-col">
                    <h3>HTML5</h3>
                    <p>
                       The HyperText Markup Language is the standard markup language for documents to be displayed in a web browser.
                       It can be assisted by other technoligies such as Cascading Style Sheets and Scripting Languages.<br><br>
                       <a href="unavailable.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
            </div>
    </section>


</body>
<script src="/js/showHide.js"></script>    
<?php require_once __DIR__ . '/footer.phtml';?>

