<?php require_once __DIR__ . '/../base.phtml';?>
<?php require_once __DIR__ . '/nav.phtml';?>
<body>

    <div class="text-box">
        <h1>Content not Available</h1>
        <p>
            Currently this content is not available for the public as it is still in development<br>
            We should be done in now time!<br><br>
            Feel free to Contact us if you have any queries!
        </p>
        <a href="contact.php" class="hero-btn">Contact Us</a>
        
    </div>
    </section>

</body>
<script src="/js/showHide.js"></script>    
<?php require_once __DIR__ . '/footer.phtml';?>

