    <body>
        <section class="sub-header">
            <nav>
                <div class="nav-links" id="navLinks">
                    <i class="fas fa-times" onclick="hideMenu()"></i>
                    <ul>
                        <li><a href="home.php">HOME</a></li>
                        <li><a href="about.php">ABOUT</a></li>
                        <li><a href="course.php">COURSE</a></li>
                        <li><a href="getStarted.php">GET STARTED</a></li>
                        <li><a href="blog.php">BLOG</a></li>
                        <li><a href="contact.php">CONTACT</a></li>
                    </ul>
                </div>
                <i class="fas fa-bars" onclick="showMenu()"></i>
            </nav>
            <h1>About Us</h1>
        </section>
        <!-- About Us Content-->
        <section class="about-us">
            <div class="row">
                <div class="about-col">
                    <h1>Largest University</h1>
                    <p>
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem quisquam minus nisi, ipsum totam laboriosam illo aliquid, 
                        vero cupiditate tenetur itaque maxime provident, non consectetur possimus. Aspernatur repudiandae animi excepturi!
                    </p>
                    <a href="" class="hero-btn red-btn">Explore Now</a>
                </div>
                <div class="about-col">
                    <img src="images/aboutus.png">
                </div>
            </div>

        </section>
    

        <!-- Footer -->
        <section class="footer">
            <h4>About Us</h4>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
            <div class="icons">
                <i class="fab fa-facebook-square"></i>
                <i class="fab fa-twitter-square"></i>
                <i class="fab fa-instagram-square"></i>
                <i class="fab fa-linkedin"></i>
            </div>
            <p>
                Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
            </p>
        </section>


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>   
    </body>