<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $data['title'] ?? '' ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

        <?php if($data == 'C++ Chapters'): ?>
            <?php foreach($data['extra_css'] as $css): ?>
                <link rel="stylesheet" type="text/css" href="<?= filter_var($css, FILTER_VALIDATE_URL) ? $css : '../css/' . $css ?>" >   
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if(isset($data['extra_css'])): ?>
        <?php foreach($data['extra_css'] as $css): ?>
            <link rel="stylesheet" type="text/css" href="<?= filter_var($css, FILTER_VALIDATE_URL) ? $css : 'css/' . $css ?>" >
        <?php endforeach; ?>
        <?php endif; ?>


    </head>