<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $data['title'] ?? '' ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/CDNSFree2/PrismJS@latest/prism.min.css">
        <script src="https://cdn.jsdelivr.net/gh/CDNSFree2/PrismJS@latest/prism.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

        <?php if(isset($data['extra_css1'])): ?>
        <?php foreach($data['extra_css1'] as $css1): ?>
            <link rel="stylesheet" type="text/css" href="<?= filter_var($css1, FILTER_VALIDATE_URL) ? $css1 : 'css/' . $css1 ?>" >
        <?php endforeach; ?>
        <?php endif; ?>

        <?php if(isset($data['extra_css2'])): ?>
        <?php foreach($data['extra_css2'] as $css2): ?>
            <link rel="stylesheet" type="text/css" href="<?= filter_var($css2, FILTER_VALIDATE_URL) ? $css2 : '../css/' . $css2 ?>" >
        <?php endforeach; ?>
        <?php endif; ?>

        <?php if(isset($data['extra_css3'])): ?>
        <?php foreach($data['extra_css3'] as $css3): ?>
            <link rel="stylesheet" type="text/css" href="<?= filter_var($css3, FILTER_VALIDATE_URL) ? $css3 : '../../css/' . $css3 ?>" >
        <?php endforeach; ?>
        <?php endif; ?>
    </head>