    <body>
        <section class="sub-header">
            <nav>
                <div class="nav-links" id="navLinks">
                    <i class="fas fa-times" onclick="hideMenu()"></i>
                    <ul>
                        <li><a href="home.php">HOME</a></li>
                        <li><a href="about.php">ABOUT</a></li>
                        <li><a href="course.php">COURSE</a></li>
                        <li><a href="getStarted.php">GET STARTED</a></li>
                        <li><a href="blog.php">BLOG</a></li>
                        <li><a href="contact.php">CONTACT</a></li>
                    </ul>
                </div>
                <i class="fas fa-bars" onclick="showMenu()"></i>
            </nav>
            <h1>Your Potential...</h1>
        </section>

<!-- Blog Page content -->
        <section class="blog-content">
            <div class="row">
                <div class="blog-left">
                    <img src="images/certificate.png">
                    <h2>Your Potential...</h2>
                    <p> 
                        CodeHeads is a free website devoted to teaching you how to program many different languages. Whether you have had any prior experience or not,
                        the tutorials on this site will walk you through all the steps to write, compile and debug your programs.
                    </p>
                    <br>
                    <p> 
                        Becoming an Expert wont happen overnight, But with patience you will get there, and CodeHeads will show you the way!
                    </p>
                    <p>
                        There are many jobs available if you decide to go down a coding path. Here are just some of them;<br>
                        <ul>
                            <li>Software application Developer</li>
                            <li>Web Developer</li>
                            <li>Computer Systems</li>
                            <li>Database Administrator</li>
                            <li>Computer Systems Analyst</li>
                            <li> Software Quality Assurance</li>
                            <li>Business Intelligence Analyst</li>
                        </ul>
                    </p>
                    <p>
                        <br>All these jobs at a high level and even after graduation could potentially put you on a salary up to £77,000 Salary!
                    </p>



                    <div class="comment-box">
                        <h3>Leave a Comment</h3>
                        <form class="comment-form">
                            <input type="text" placeholder="Enter Name">
                            <input type="email" placeholder="Enter Email">

                            <textarea rows="5" placeholder="Your comment"></textarea>
                        
                            <button type="submit" class="hero-btn red-btn">Post Comment</button>
                            
                        </form>
                    </div>
                </div>
                <div class="blog-right">
                    <h3>Post Categories</h3>
                    <div>
                        <span>C++ Language</span>
                        <span>23</span>
                    </div>
                    <div>
                        <span>C Language</span>
                        <span>56</span>
                    </div>
                    <div>
                        <span>HTML</span>
                        <span>76</span>
                    </div>
                </div>
            </div>
        </section>


        <!-- Footer -->
        <section class="footer">
            <h4>About Us</h4>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
            <div class="icons">
                <i class="fab fa-facebook-square"></i>
                <i class="fab fa-twitter-square"></i>
                <i class="fab fa-instagram-square"></i>
                <i class="fab fa-linkedin"></i>
            </div>
            <p>
                Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
            </p>
        </section>


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>   
    </body>