    <body>
        <section class="sub-header">
            <nav>
                <div class="nav-links" id="navLinks">
                    <i class="fas fa-times" onclick="hideMenu()"></i>
                    <ul>
                        <li><a href="home.php">HOME</a></li>
                        <li><a href="about.php">ABOUT</a></li>
                        <li><a href="course.php">COURSE</a></li>
                        <li><a href="getStarted.php">GET STARTED</a></li>
                        <li><a href="blog.php">BLOG</a></li>
                        <li><a href="contact.php">CONTACT</a></li>
                    </ul>
                </div>
                <i class="fas fa-bars" onclick="showMenu()"></i>
            </nav>
            <h1>Contact Us</h1>
        </section>
        <!-- Contact Us -->
        <section class="location">

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2481.9070739997414!2d
            -0.1281918840274987!3d51.53326421663241!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761b3c54efa6e1%3A0xc7053ab04745950d!
            2sGoogle%20UK!5e0!3m2!1sen!2suk!4v1643791261748!5m2!1sen!2suk" 
            width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

        </section>
        <section class="contact-us">
            <div class="row">
                <div class="contact-col">

                    <div>
                        <i class="fas fa-home"></i>
                        <span>
                            <h5>6 Pancras Sq, Google UK</h5>
                            <p>London N1C 4AG</p>
                        </span>
                    </div>

                    <div>
                        <i class="fas fa-phone"></i>
                        <span>
                            <h5>+ 01889 272307</h5>
                            <p>Monday to Friday, 9am to 5pm</p>
                        </span>
                    </div>

                    <div>
                        <i class="fas fa-envelope"></i>
                        <span>
                            <h5>info@codeheads.com</h5>
                            <p>Email Us Your Query</p>
                        </span>
                    </div>
                </div>

                <div class="contact-col">

                    <form action="form-handler.php" method="post">
                        <input type="text" name="name" placeholder="Enter Your Name" required>
                        <input type="email" name="email "placeholder="Enter Email Address" required>
                        <input type="text" name="subject" placeholder="Enter Your Subject" required>
                        <textarea rows="8" name="message" placeholder="Message"></textarea>
                        <button type="submit" class="hero-btn red-btn">Send Message</button>

                    </form>
                    
                </div>
            </div>
        </section>


        <!-- Footer -->
        <section class="footer">
            <h4>About Us</h4>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
            <div class="icons">
                <i class="fab fa-facebook-square"></i>
                <i class="fab fa-twitter-square"></i>
                <i class="fab fa-instagram-square"></i>
                <i class="fab fa-linkedin"></i>
            </div>
            <p>
                Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
            </p>
        </section>


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>   
    </body>