<?php require_once __DIR__ . '/../../base.phtml';?>
<?php require_once __DIR__ . '/cplusNav.phtml';?>
<body>
<!--------------------------------------- Head Section -------------------------------------->
    <div class="text-box">
        <h1>Learning C++</h1>
        <p>
            C++ is the extended version of the C Language. This object-oriented language offers a clearer understanding of Various<br>
            programs and helps develop high-performance applications that can be used on multiple platforms.
        </p> 
    </div>
    </section>
<!------------- Chapter Section ------------------>
    <section class="cpp-chapter">
        <h1>Chapters for this Course</h1>
        <p>
            C++ (pronounced ‘C plus plus’) is object-oriented computer language created by notable computer scientist<b> Bjorne
            Stroustrop</b> as part of the evolution of the C family of languages. It was developed as a cross-platform improvement
            of C to provide developers with a higher degree of control over memory and system resources.
        </p>
        <p>
            Some call C++ “C with classes” because it introduces object-oriented programming principles, including the use of
            define classes, to the C programming language framework. Over time, C++ has remained a very useful language
            not only in computer programming itself, but in teach new programmers about how object-oriented programming
            works. However, it does not support only object-oriented, but also procedural and functional. Thanks to its high
            flexibility and scalability, C++ can be used to develop a broad range of software, application, browsers, Graphical
            User Interfaces (GUIs), operating systems, and games. 
        </p>
        <p>
            Today C++ is still very appreciated for its notable portability which allows developers to create programs that can
            run on different operating systems or platforms very easily. Despite being a high-level language, since C++ is still
            close to C it can be used for low-level manipulation due to its close relation with machine language.
        </p>

        <div class="cpp-chapter-col">                                   <!--Chapter Column Start -->
            <div class="flexbox-container">                             <!--Chapter Left Start -->

                <div class="chapter-header">                            <!--Chapter Header Start -->
                    <a name="Chapter1"></a>
                    <div class="chapter-header-num">Chapter 1</div>
                    <div class="chapter-header-title">C++ Basics</div>
                </div>                                                  <!--Chapter Header End -->

                <div class="cpp-chapter-list">                          <!--Chapter List Start -->
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.1</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_1.php">
                            Statements and the Structure of a Program
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.2</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_2.php">
                            Comments
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.3</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_3.php">
                            Introduction to Objects and Variables
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.4</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_4.php">
                            Variable Assignment
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.5</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_5.php">
                            Introduction to IOstream: cout, cin and endl
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.6</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_6.php">
                            Uninitialized variables and undefined behavior
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.7</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_7.php">
                            Keywords and naming identifiers
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.8</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_8.php">
                            Whitespace and basic formatting
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.9</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_9.php">
                            Introduction to literals and operators
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.10</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_10.php">
                            Expressions
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.11</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_11.php">
                            Developing your First Program
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.X</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_X.php">
                            End of Chapter Summary and Quiz
                            </a>
                        </div>
                    </div>

                </div>      <!--Chapter List End -->
            </div>          <!--Chapter Left End -->
        </div>              <!--Chapter Column End -->

        <div class="cpp-chapter-col">           <!--Chapter Column Start -->

            <div class="chapter-header">                            <!--Chapter Header Start -->
                <a name="Chapter1"></a>
                <div class="chapter-header-num">Chapter 2</div>
                <div class="chapter-header-title">C++ Basics: Functions and Files</div>
            </div>                                                  <!--Chapter Header End -->

            <div class="cpp-chapter-list">                          <!--Chapter List Start-->
                <div class="lesson-row">
                    <div class="lesson-row-num">2.1</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_1.php">
                        Introduction to Functions
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.2</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_2.php">
                        Return Values
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.3</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_2.php">
                        Introduction to Function Parameters and Arguments
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.4</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_4.php">
                        Introduction to Local Scope
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.5</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_5.php">
                        Why Functions are Useful
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.6</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_6.php">
                        Forward Declaration and Definitions
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.7</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_7.php">
                        Programs with Multiple Code Files
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.8</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_8.php">
                        Naming Collisions and an Introduction to Namespaces
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.9</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_9.php">
                        Introduction to the Preprocessor
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.10</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_10.php">
                        Header Files
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.11</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_11.php">
                        Header Guards
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.12</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_12.php">
                        How to design your First Program
                        </a>
                    </div>
                </div>
                <div class="lesson-row">
                    <div class="lesson-row-num">2.X</div>
                    <div class="lesson-row-title">
                        <a href="chapter2/2_X.php">
                        End of Chapter Summary and Quiz
                        </a>
                    </div>
                </div>

            </div><!--Chapter List End -->
        </div><!--Chapter Column End -->
    </section>

    <script src="../js/showHide.js"></script>   
</body>

<?php require_once __DIR__ . '/../footer.phtml';?>

