<?php require_once __DIR__ . '/../base.phtml'; ?>
<?php require_once __DIR__ . '/header.phtml'; ?>

<body>
    <div class="container">
        <?php if (isset($data['error'])): ?>
        <div class="row g-3 ErrorMessage">
            <div class="error"><?= $data['error'] ?></div>
        </div>
        <?php endif; ?>

        <!-- Form Start -->
        <form class="row g-3" id="surveyForm" action="<?= $data['action'] ?>" method="post">
            <?php if (isset($data['record']['id'])): ?>
                <input type="hidden" name="id" value="<?= $data['record']['id'] ?>"/>
            <?php endif; ?>
            <?php if (isset($data['currentPage'])): ?>
                <input type="hidden" name="page" value="<?= $data['currentPage'] ?>"/>
            <?php endif; ?>
            

                <h1>Contact Form:</h1>
                <!-- Row 1 Start -->
                <div class="row">
                    <div class="col-md-12">
                    <h6 for="contact_name">Name</h6>
                        <input type="text" class="form-control" id="contact_name" name="contact_name" value="<?= htmlspecialchars($data['record']['contact_name'] ?? '' )?>" required><br>
                    </div>
                    <div class="col-12">
                        <h6 for="contact_email">Contact Email</h6>
                        <input type="email" class="form-control" id="contact_email" name="contact_email" value="<?= htmlspecialchars($data['record']['contact_email'] ?? '' )?>" required><br>
                    </div>
                    <div class="col-12">
                        <h6 for="contact_subject">Subject</h6>
                        <input type="text" class="form-control" id="contact_subject" name="contact_subject" value="<?= htmlspecialchars($data['record']['contact_subject'] ?? '' )?>" required> <br>
                    </div>
                    <div class="col-12">
                        <h6 for="contact_message">Message</h6>
                        
                        <textarea rows="4" class="form-control" name="contact_message" id="mytextbox" required><?php echo $data['record']['contact_message'] ?? ''?> </textarea>                 
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <button class="hero-btn" type="submit">Submit</button>
                        <a href="index.php?page=<?= $data['currentPage'] ?>" role="button">
                    </div>
                    <div class="col-md-4">
                        <li class="backBtn"><?php if(isset($data['currentPage'])): ?> <a class="backBtn" 
                        href="index.php?page=<?= $data['currentPage'] ?>" role="button">Back to Records</a> <?php endif; ?></li>
                    </div>
                </div>
                    

                    
                
                               
                <!-- Rw 1 End -->

            <!-- Tab 2 Start -->

            
        </form> <!--Form End -->
    </div>
    
<</body>

<?php require_once __DIR__ . '/footer.phtml'; ?>
