
    <body>
        <div class="bg-color"><!--bg color Start-->

            <section class="top-bar">
                <nav>
                    <div class="nav-links" id="navLinks">
                        <i class="fas fa-times" onclick="hideMenu()"></i>
                        <ul>
                            <li><a href="../index.html">HOME</a></li>
                            <li><a href="../about.html">ABOUT</a></li>
                            <li><a href="../course.html">COURSE</a></li>
                            <li><a href="../getStarted.html">GET STARTED</a></li>
                            <li><a href="../blog.html">BLOG</a></li>
                            <li><a href="../contact.html">CONTACT</a></li>
                        </ul>
                    </div>
                    <i class="fas fa-bars" onclick="showMenu()"></i>
                </nav>
            </section>
            <section class="lesson-content">

                <div class="lesson-container">
                    <div class="content">
                        <h1>Chapter 1.9 - Introduction to Literals and Operators</h1>
                        <hr>

                        <div class="part-content">
                            <h2>Literals</h2>
                            <p>
                                Consider the following statements:
                            </p>
                                <pre>
                                    <code class="language-cpp line-numbers">
                                        std::cout << "Hello World!";
                                        int x { 5 };
                                    </code>
                                </pre>
                            <p>
                                The above statements are <b>literals</b>. A literal is a fixed value that has been directly inserted into the source code. 
                                Literals and variables both have a value and type. However, the value of a literal is fixed and cannot be changed, 
                                whereas the value of a variable can be changed through initialization and assignment.
                            </p>
                                

                        </div>
                        <div class="part-content">

                            <h2>Operators</h2>
                            <p>
                                In mathematics, an <b>operation</b> is a mathematical calculation involving zero or more input values (called <b>operands</b>) 
                                that produces a new output value. The specific operation to be performed is denoted by a construct (typically 
                                a symbol or pair of symbols) called an <b>operator</b>.
                            </p>
                            <p>
                                You are likely familiar with standard arithmetic operators from common usage in mathematics, including addition, 
                                subtraction, multiplication, and division. In C++, assignment (=) is an operator as well as are insertion (<<) and extraction (>>). 
                                Some operators use more than one symbol, such as the equality operator (==), which allows us to compare two values to see if they are equal. 
                                There are also several operators that are words (new, delete, throw).
                            </p>
                            <p>
                                The number of operands than an operator takes as input is called the operators arity. Operators in C++ have three different arities:
                            </p>
                            <p>
                                <b>Unary</b> - These operators act on one operand. <br>
                                <b>Binary</b> - These operators act on two operands known as left and right.<br>
                                <b>Ternary</b> - These operators act on three operands.
                            </p>

                        </div>
                        
                    </div>

                        <div class="prev-next">
                            <div class="prev-next-inline">
                                <a class="nav-link" href="chapter1_10.html">
                                    <div class="nav-button nav-button-next">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Next Lesson</div>
                                            <div class="nav-button-lesson">
                                                <span class="nav-button-lesson-number">1.10</span>
                                                Expressions
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <a class="nav-link" href="../cplusChapter.html">
                                    <div class="nav-button nav-button-index">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-home" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Back to Table of Contents</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="nav-link" href="chapter1_8.html">
                                    <div class="nav-button nav-button-prev">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Previous Lesson</div>
                                            <div class="nav-button-lesson">
                                                <span class="nav-button-lesson-number">1.8</span>
                                                Whitespace and Basic Formatting
                                            </div>
                                        </div>
                                    </div>
                                </a>

                            </div>
                        </div>
                </div>


         </div>
                
            </section>
    
            <!-- Footer -->
            <section class="footer">
                <h4>About Us</h4>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
                <div class="icons">
                    <i class="fab fa-facebook-square"></i>
                    <i class="fab fa-twitter-square"></i>
                    <i class="fab fa-instagram-square"></i>
                    <i class="fab fa-linkedin"></i>
                </div>
                <p>
                    Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
                </p>
            </section>

         </div> <!--bg color End -->
        


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>
     <script>
        function show_hide(element)
        {
           var myAnswer = element.nextElementSibling;

           var displaySetting = myAnswer.style.display;

           var quizButton = element;

           if(displaySetting=="inline-block"){
               myAnswer.style.display = 'none';

               quizButton.innerHTML = 'Show Solution';
           }
           else
           {
               myAnswer.style.display = 'inline-block';
               quizButton.innerHTML = 'Hide Solution';
           }
        }
    </script>
    </body>
