    <body>
        <section class="sub-header">
            <nav>
                <div class="nav-links" id="navLinks">
                    <i class="fas fa-times" onclick="hideMenu()"></i>
                    <ul>
                        <li><a href="home.php">HOME</a></li>
                        <li><a href="about.php">ABOUT</a></li>
                        <li><a href="course.php">COURSE</a></li>
                        <li><a href="getStarted.php">GET STARTED</a></li>
                        <li><a href="blog.php">BLOG</a></li>
                        <li><a href="contact.php">CONTACT</a></li>
                    </ul>
                </div>
                <i class="fas fa-bars" onclick="showMenu()"></i>
            </nav>

            <h1>Choose Your Language</h1>   
        </section>

        <!-- Choose Content -->
        <section class="choose-content">
            <h1>Courses We Offer</h1>
            <p>
                Learning a Programming Language is easy when you get taught the correct way!<br> Begin now and start your path to a New Career!<br>

                All of the courses we offer are for new programmers who dont have any previous knowledge of coding<BR>
                So be ready to turn into a pro in no time!
            </p>

            <div class="row">
                <div class="choose-col">
                    <h3>C++</h3>
                    <p>
                        C++ is the extended version of the C Language. This object-oriented language offers a clearer understanding of Various
                        programs and helps develop high-performance applications that can be used on multiple platforms.<br><br>
                        <a href="../../cpp-content/cppChapters.php">
                        <button type="submit" class="hero-btn solid-btn">Get Started</button>
                        </a>
                    </p>
                </div>
                <div class="choose-col">
                    <h3>C Language</h3>
                    <p>
                        C is a powerful general-purpose programming language. It can be used to develop software like operating systems, databases, compilers,
                        and so on. C Programming is an excellent language to learn programming for begginers<br><br>
                        <button type="submit" class="hero-btn solid-btn">Get Started</button>
                    </p>
                </div>
                <div class="choose-col">
                    <h3>HTML5</h3>
                    <p>
                       The HyperText Markup Language is the standard markup language for documents to be displayed in a web browser.
                       It can be assisted by other technoligies such as Cascading Style Sheets and Scripting Languages.<br><br>
                       <button type="submit" class="hero-btn solid-btn">Get Started</button>
                    </p>
                </div>
            </div>
        </section>




<!-- Footer -->
        <section class="footer">
            <h4>About Us</h4>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
            <div class="icons">
                <i class="fab fa-facebook-square"></i>
                <i class="fab fa-twitter-square"></i>
                <i class="fab fa-instagram-square"></i>
                <i class="fab fa-linkedin"></i>
            </div>
            <p>
                Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
            </p>
        </section>


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>   
    </body>