

    <body>
        <section class="header">
            <nav>
                <div class="nav-links" id="navLinks">
                    <i class="fas fa-times" onclick="hideMenu()"></i>
                    <ul>
                        <li><a href="home.php">HOME</a></li>
                        <li><a href="about.php">ABOUT</a></li>
                        <li><a href="course.php">COURSE</a></li>
                        <li><a href="getStarted.php">GET STARTED</a></li>
                        <li><a href="blog.php">BLOG</a></li>
                        <li><a href="contact.php">CONTACT</a></li>
                    </ul>
                </div>
                <i class="fas fa-bars" onclick="showMenu()"></i>
            </nav>

        <div class="text-box">
            <h1>Welcome to CodeHeads</h1>
            <p>
                The Best platform to start your Career in Programming!<br><br>
                Learning a Programming Language is easy when you get taught the correct way!<br> Begin now and start your path to a New Career!
            </p>
            <a href="getStarted.html" class="hero-btn">Get Started</a>
        </div>    
        </section>
        
        <section class="course">
            <h1>Courses We Offer</h1>
            <p>
                All of the courses we offer are for new programmers who dont have any previous knowledge of coding<BR>
                So be ready to turn into a pro in no time!
            </p>

            <div class="row">
                <div class="course-col">
                    <h3>C++</h3>
                    <p>
                        C++ is the extended version of the C Language. This object-oriented language offers a clearer understanding of Various
                        programs and helps develop high-performance applications that can be used on multiple platforms.<br><br>
                        <a href="cplusChapter.html">
                            <button type="submit" class="hero-btn solid-btn">Get Started</button>
                        </a>
                    </p>
                </div>
                <div class="course-col">
                    <h3>C Language</h3>
                    <p>
                        C is a powerful general-purpose programming language. It can be used to develop software like operating systems, databases, compilers,
                        and so on. C Programming is an excellent language to learn programming for begginers<br><br>
                        <button type="submit" class="hero-btn solid-btn">Get Started</button>
                    </p>
                </div>
                <div class="course-col">
                    <h3>HTML5</h3>
                    <p>
                       The HyperText Markup Language is the standard markup language for documents to be displayed in a web browser.
                       It can be assisted by other technoligies such as Cascading Style Sheets and Scripting Languages.<br><br>
                       <button type="submit" class="hero-btn solid-btn">Get Started</button>
                    </p>
                </div>
            </div>
        </section>

        <!------ Campus --------->

        <section class="campus">
            <h1>Our Global Campus</h1>
            <p>
                Our courses are used globally for anybody who wants to start programming. We have provided the Best Programming Influences all over the globe.<br>
                Who are now on High Paid jobs, and famous influencers
             </p>
            <div class="row">
                <div class="campus-col">
                    <img src="images/london.png">
                    <div class="layer">
                        <h3>LONDON</h3>
                    </div>
                </div>
                <div class="campus-col">
                    <img src="images/newyork.png">
                    <div class="layer">
                        <h3>NEW YORK</h3>
                    </div>
                </div>
                <div class="campus-col">
                    <img src="images/washington.png">
                    <div class="layer">
                        <h3>WASHINGTON</h3>
                    </div>
                </div>
            </div>
        </section>

<!-- Facilities -->

        <section class="facilities">
            <h1>People We Helped Become Who They Are Now</h1>
            <p>Below is a list of people our turorials helped assist<br> in learning how to program</p>

            <div class="row">
                <div class="facilities-col">
                    <img src="images/jason.png">
                    <h3>Jason Turner</h3>
                    <p>
                        Jason is an award-winning C++ keynote speaker and trainer. He has spoken and provided training at more than 10
                        conferences and 15 companies. Jason utilizes his C++ knowledge and unique training style of more than two
                        decades to help organizations write clean, maintainable, and efficient programs. And He learnt all that at CodeHeads!
                    </p>
                </div>
                <div class="facilities-col">
                    <img src="images/wasik.png">
                    <h3>Wasik Farhan-Roopkotha</h3>
                    <p>
                        Wasik is  Bangladeshis youngest C programmer in the world. At the age of 6 he was developing multiple games.
                        And has now been given fundings by the <b>Technology Division</b> for creating a game about the liberation war of the country!
                    </p>
                </div>
                <div class="facilities-col">
                    <img src="images/mosh.png">
                    <h3>Mosh Hamedani</h3>
                    <p>
                        Better known online as <b>Programming with Mosh</b>, is an Australien educational YouTuber
                        and Software Engineer specializing in web application development. Most things he has learnt about the 
                        HTML language has been From CodeHeads.<br>
                        "CodeHeads has brought me where i am today, with over 2 million subscribers. I am constantly helping new people everyday with there future
                        in programming. CodeHeads is a great place to learn Any language that they offer"
                        
                    </p>
                </div>
            </div>
        </section>

<!-- Testimonials -->

        <section class="testimonials">
            <h1>What our Students Say</h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>

            <div class="row">
                <div class="testimonials-col">
                    <img src="images/user1.png">
                    <div>
                        <p>
                            The tutorials are extremely detailed and taught in a way anybody can understand!
                            
                        </p>
                        <h3>Christopher</h3>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="far fa-star"></i>
                    </div>
                </div>

                <div class="testimonials-col">
                    <img src="images/user2.png">
                    <div>
                        <p>
                            Learning C++ by CodeHeads has given me such a wide oppotunity in my life. I have now got a job at a HighTech Company designing
                            High-Performance Programs!
                        </p>
                        <h3>Jay</h3>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star-half-alt"></i>
                    </div>
                </div>
            </div>
        </section>

        <!-- Call to Action -->

        <section class="cta">
            <h1>Start your Journey Now!</h1>
            <a href="getStarted.html" class="hero-btn">Get Started!</a>

        </section>


<!-- Footer -->
        <section class="footer">
            <h4>About Us</h4>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
            <div class="icons">
                <i class="fab fa-facebook-square"></i>
                <i class="fab fa-twitter-square"></i>
                <i class="fab fa-instagram-square"></i>
                <i class="fab fa-linkedin"></i>
            </div>
            <p>
                Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
            </p>
        </section>


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>   
    </body>