<?php require_once __DIR__ . '/../../../base.phtml'; ?>
<?php require_once __DIR__ . '/../cplusNavLesson.phtml'; ?>

<body>

    <section class="lesson-content"> <!-- Lesson Content Start -->
        <div class="lesson-container"> <!-- Lesson Container Start -->
            <div class="content">       <!-- Content Start -->
                <h1>Chapter 1.2 - Comments</h1>
                <hr>
                <div class="part-content">
                    <p>
                        A <b>comment</b> is a programmer-readable note that is inserted directly into the source code of the program. 
                        Comments are ignored by the compiler and are for the programmers use only. In C++ there are two 
                        different styles of comments, both of which serve the same purpose to help programmers.
                    </p>
                </div>

                <div class="part-content">
                    <h2>Single Line Comments</h2>
                    <p>
                        the “//” symbol begins a C++ single line comment, which tells the compiler to ignore everything after 
                        the symbol to the end of the line. For example:
                    </p>
                        <pre>
                            <code class="language-cpp line-numbers">
                                std::cout << "Hello World";     //Everything from here is ignored
                            </code>
                        </pre>
                    <p>
                        Typically, the single line comment is used to make quick comments about a single line of code.
                    </p>
                </div>

                <div class="part-content">
                    <h2>Multi-line Comments</h2>
                    <p>
                        The /* and */ pair of symbols denotes a C-style multi-line comment. 
                        Everything between these symbols is ignored. For example:
                    </p>
                        <pre>
                            <code class="language-cpp line-numbers">
                                /*This is a Multi-line Comment.
                                This Line will be ignored
                                so will this one. */
                            </code>
                        </pre>

                        <div class="lesson-warning">
                            <p>
                                <mark>Warning</mark> – Using multi-line comments inside of other multi-line comments, 
                                can cause some issues with the compiler thinking that it is not a comment. Wrapping 
                                single-line comments in a multi-line is okay though.
                            </p>
                        </div>
                        <div class="lesson-practice">
                            <p>
                                <mark>Best Practice</mark> – comment your code liberally and write your commands as if you are
                                speaking to someone who has no idea what the code does. Do not assume you will 
                                remember why you made specific choices.
                            </p>
                        </div>
                    <p>
                        It’s common for programmers to also comment out their code. A few reasons why you should do this are as follows:
                        <ul>
                            <li>You are working on a new piece of code that will not compile yet</li>
                            <li>You have written code that cnompiles but not correctly, and you do not have time too fix it</li>
                            <li>You want to replace one piece of code with another, without having to delete the other section</li>
                            <li>You have written code that works fine, but you do not want to use it for now in your current execution of the program.</li>
                        </ul>
                    </p>
                </div>

                <div class="prev-next">
                    <div class="prev-next-inline">
                        <a class="nav-link" href="1_3.php">
                            <div class="nav-button nav-button-next">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Next Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.3</span>
                                        Introuduction to Objects and Variables
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="../cplusChapter.php">
                            <div class="nav-button nav-button-index">
                                <div class="nav-button-icon">
                                    <i class="fas fa-home" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Back to Table of Contents</div>
                                </div>
                            </div>
                        </a>
                        <a class="nav-link" href="1_1.php">
                            <div class="nav-button nav-button-prev">
                                <div class="nav-button-icon">
                                    <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                </div>
                                <div class="nav-button-text">
                                    <div class="nav-button-title">Previous Lesson</div>
                                    <div class="nav-button-lesson">
                                        <span class="nav-button-lesson-number">1.1</span>
                                        Statements & Structure of a Program
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

            </div>  <!-- Content End -->
        </div> <!-- Lesson Container Start -->
    </section> <!-- Lesson Content End -->
 
<script src="/../js/quiz.js"></script>

</body>

<?php require_once __DIR__ . '/../../footer.phtml'; ?>
