<?php require_once __DIR__ . '/base.phtml';?>
<?php require_once __DIR__ . '/nav.phtml';?>

<body>

    <div class="text-box">
        <h1>Contact us</h1>
    </div>
    </section>

<!--------- Contact Page ------------------>
    <section class="contact-us">
        <div class="row">
            <div class="contact-col">
                <div>
                    <i class="fas fa-home"></i>
                    <span>
                        <h5>6 Pancras Sq, Google UK</h5>
                        <p>London N1C 4AG</p>
                    </span>
                </div>
                <div>
                    <i class="fas fa-phone"></i>
                    <span>
                        <h5>+ 01889 272307</h5>
                        <p>Monday to Friday, 9am to 5pm</p>
                    </span>
                </div>
                <div>
                    <i class="fas fa-envelope"></i>
                    <span>
                        <h5>info@codeheads.com</h5>
                        <p>Email Us Your Query</p>
                        <p>
                            We will get back to you as soon as we can!
                        </p>
                    </span>
                </div>
            </div>
            <div class="contact-col">
                <form action="<?= $data['action'] ?>" method="post">

                    <?php if (isset($data['record']['id'])): ?>
                        <input type="hidden" name="id" value="<?= $data['record']['id'] ?>"/>
                    <?php endif; ?>

                    <?php if (isset($data['currentPage'])): ?>
                        <input type="hidden" name="page" value="<?= $data['currentPage'] ?>"/>
                    <?php endif; ?>

                    <input type="text" name="contact_name" id="contact_name" placeholder="Enter Your Name" required>

                    <input type="email" name="contact_email" id="contact_email" placeholder="Enter Email Address" required>

                    <input type="text" name="contact_subject" id="contact_subject" placeholder="Enter Your Subject" required>

                    <textarea rows="8" name="contact_message" id="message" placeholder="Message"></textarea>

                    <button type="submit" class="hero-btn red-btn">Send Message</button>
                </form> 
            </div>
        </div>
    </section>

    <section class="location">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2481.9070739997414!2d
        -0.1281918840274987!3d51.53326421663241!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761b3c54efa6e1%3A0xc7053ab04745950d!
        2sGoogle%20UK!5e0!3m2!1sen!2suk!4v1643791261748!5m2!1sen!2suk" 
        width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </section>



</body>
<?php require_once __DIR__ . '/footer.phtml';?>

