<section class="header">
    <nav>
        <div class="nav-links" id="navLinks">
            <i class="fas fa-times" onclick="hideMenu()"></i>
                <ul>
                    <li><a href="home.php">HOME</a></li>
                    <li><a href="courses.php">COURSES</a></li>
                    <li><a href="about.php">ABOUT</a></li>
                    <li><a href="blog.php">BLOG</a></li>
                    <li><a href="contact.php">CONTACT</a></li>
                </ul>
        </div>
        <i class="fas fa-bars" onclick="showMenu()"></i>
    </nav>
