
    <body>
        <div class="bg-color"><!--bg color Start-->

            <section class="top-bar">
                <nav>
                    <div class="nav-links" id="navLinks">
                        <i class="fas fa-times" onclick="hideMenu()"></i>
                        <ul>
                            <li><a href="../index.html">HOME</a></li>
                            <li><a href="../about.html">ABOUT</a></li>
                            <li><a href="../course.html">COURSE</a></li>
                            <li><a href="../getStarted.html">GET STARTED</a></li>
                            <li><a href="../blog.html">BLOG</a></li>
                            <li><a href="../contact.html">CONTACT</a></li>
                        </ul>
                    </div>
                    <i class="fas fa-bars" onclick="showMenu()"></i>
                </nav>
            </section>
            <section class="lesson-content">

                <div class="lesson-container">
                    <div class="content">
                        <h1>Chapter 2.2 - Return Values</h1>
                        <hr>

                        <div class="part-content">
                            <h2>Return Values</h2>
                            <p>
                                When you write a user-defined function, you get to determine whether your function will
                                return a value back to the caller or not. To return a value back to the caller, 
                                two things are needed. 
                            </p>
                            <p>
                                First, your function must indicate what type of value will be returned. This is done by setting 
                                the functions <b>return type</b>, which is the type that is defined before the functions name. 
                                Second, inside the function that will return a value, we use a <b>return statement</b> to indicate the 
                                specific value being returned to the caller. The specific value returned from a function is called a <b>return 
                                value</b>. When the return statement is executed, the return value is copied from the function back to the caller. 
                                This process is called <b>return by value</b>.
                            </p>
                        </div>
                        <div class="part-content">
                            <h2>Void Return Values</h2>
                        </div>
                            <p>
                                Functions are not required to return a value. To tell the compiler that a 
                                function does not return a value, a return type of void is used. Here is an 
                                example.
                            </p>
                                <pre>
                                    <code class="language-cpp line-numbers">
                                        void doPrint()  // void is the return type
                                        {
                                            std::cout <<  "In doPrint()" << '\n';
                                            // This function does not return a value so no return statement is needed.
                                        }
                                    </code>
                                </pre>
                            <p>
                                This function has a return type of void, indicating that it does not return a value. 
                                Since it does not return a value, no return statement is needed. 
                            </p>
                            <div class="lesson-practice">
                                <mark>Best Practice - </mark>follow the DRY best practice: “Don’t Repeat Yourself”. 
                                If you need to do something more than once, consider how to modify your code to remove as 
                                much redundancy as possible. Variable can be used to store the results of calculations that 
                                need to be used more than once. Functions can be used to define a sequence of statements we want 
                                to execute more than once. And loops can be used to execute a statement more than once.
                            </div>
                            <h5>Conclusion</h5>
                            <p>
                                Return values provide a way for functions to return a single value back to the 
                                function’s caller. And functions provide a way to minimize redundancy in our programs. 
                            </p>
                               
                        <div class="prev-next">
                            <div class="prev-next-inline">
                                <a class="nav-link" href="chapter2_3.html">
                                    <div class="nav-button nav-button-next">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Next Lesson</div>
                                            <div class="nav-button-lesson">
                                                <span class="nav-button-lesson-number">2.3</span>
                                                Introduction to Function Parameters and Arguments
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <a class="nav-link" href="../cplusChapter.html">
                                    <div class="nav-button nav-button-index">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-home" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Back to Table of Contents</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="nav-link" href="chapter2_1.html">
                                    <div class="nav-button nav-button-prev">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Previous Lesson</div>
                                            <div class="nav-button-lesson">
                                                <span class="nav-button-lesson-number">2.1</span>
                                                Introduction to Functions
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
                
            </section>
    
            <!-- Footer -->
            <section class="footer">
                <h4>About Us</h4>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
                <div class="icons">
                    <i class="fab fa-facebook-square"></i>
                    <i class="fab fa-twitter-square"></i>
                    <i class="fab fa-instagram-square"></i>
                    <i class="fab fa-linkedin"></i>
                </div>
                <p>
                    Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
                </p>
            </section>

         </div> <!--bg color End -->
        


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>
     <script>
        function show_hide(element)
        {
           var myAnswer = element.nextElementSibling;

           var displaySetting = myAnswer.style.display;

           var quizButton = element;

           if(displaySetting=="inline-block"){
               myAnswer.style.display = 'none';

               quizButton.innerHTML = 'Show Solution';
           }
           else
           {
               myAnswer.style.display = 'inline-block';
               quizButton.innerHTML = 'Hide Solution';
           }
        }
    </script>
    </body>
