<?php require_once __DIR__ . '/../base.phtml'; ?>

<body id="overview-bg">
    <?php require_once __DIR__ .'/header.phtml'; ?>
    <div class="container">
        <main>
            <div class="row">
                <div class="col-md-8">
                    <h2 class="titleHead">Contact Forms</h2>
                </div>
                <div class="col-md-4">
                    <input type="text" id="myInput" onkeyup="tableSearch()"class="search form-control" placeholder="Search PO Number...">
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <?php if (isset($data['flash']['message'])): ?>
                    <div class="alert alert-<?= $data['flash']['type'] ?? 'success' ?>" role="alert">
                        <?= $data['flash']['message'] ?>
                    </div>
                    <?php endif; ?>
                    
                        <table class="table table-bordered" id="myTable">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Contact Name</th>
                                <th>Subject</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($data['records'] as $row): ?>
                                <?php if(isset($data['flash']['id']) && (int) $row['id'] === $data['flash']['id']): ?><tr class="table-info"><?php else: ?><tr><?php endif; ?>
                                <td><b><?= $row['id'] ?></b></td>
                                <td><?= $row['contact_name'] ?></td>
                                <td><?= $row['contact_subject'] ?></td>
                                <td>
                                    
                                    <a href="edit.php?id=<?= $row['id'] ?>&page=<?= $data['currentPage'] ?>"><i class="fas fa-edit"></i></i></a>
                                    <?php if ($_SESSION['userRole'] === 'ADMIN'): ?>

                                    <a onclick="return confirm_delete(<?= $row['id'] ?>);" href="delete.php?id=<?= $row['id'] ?>&page=<?= $data['currentPage'] ?>">
                                    <i class="fas fa-trash"></i></a>
                                    
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                </div>

                <?php if ($data['maxPages'] > 1): ?>
                <div class="col-md-12 col-lg-12">
                    <nav aria-label="Navigation" >
                        <ul class="pagination pagination-sm justify-content-center">
                            <?php for($i=$data['startPage']; $i<=$data['endPage']; $i++): ?>
                            <li class="page-item<?= $i === $data['currentPage'] ? ' active': '' ?>"><a class="page-link" href="index.php?page=<?= $i ?>"><?= $i ?></a></li>
                            <?php endfor; ?>
                        </ul>
                    </nav>
                </div>
                <?php endif; ?>
            </div>
        </main>
    </div>

    <script>
        function confirm_delete(id) {
            return confirm('Are you sure you want to delete record with id ' + id + '?');
        }
    </script>

    <script src="../js/search.js"></script>

</body>

<?php require_once __DIR__ . '/footer.phtml'; ?>
