<section class="nav-lesson">
    <div class="top-bar">
        <nav>
            <div class="nav-links" id="navLinks">
                <i class="fas fa-times" onclick="hideMenu()"></i>
                    <ul>
                        <li><a href="/../home.php">HOME</a></li>
                        <li><a href="/../courses.php">COURSES</a></li>
                        <img src="/img/logo.png" class="logo-nav" alt="logo">
                        <li><a href="/../about.php">ABOUT</a></li>
                        <li><a href="/../contact.php">CONTACT</a></li>
                    </ul>
            </div>
            <i class="fas fa-bars" onclick="showMenu()"></i>
        </nav>
    </div>
    

    <!-- <div id="top-bar">
	<nav>
		<div class="nav-container">
			<div class="nav-links" id="navLinks">
                <ul>
                    <li><a href="/home.php">CodeHeads</a></li>
                    <li><a href="/admin/logout.php">Logout - [<?= ucfirst($_SESSION['username']) ?>]</a></li>
                </ul>
        	</div>
		</div>
		
	</nav>
</div> -->