<?php require_once __DIR__ . '/../../base.phtml';?>
<?php require_once __DIR__ . '/coreNav.phtml';?>
<body>
<!--------------------------------------- Head Section -------------------------------------->
    <div class="text-box">
        <h1>Core Programming Concepts</h1>
    </div>
    </section>
<!------------- Chapter Section ------------------>
    <section class="core-chapter">
        <h2>Chapters & Overview for this Course</h2>
        <p>
            Computer programming is the process of performing a particular computation, usually by designing/building an executable computer program.
            Programming involves tasks such as analysis, generating algorithms, profiling algorithms accuracy and resource consumption, and the implementation of algorithms
        </p>
        <p>
            In 1883 the first ever programming language was developed when Ada Lovelace and Charles Babbage worked together on the Analytical Engine, which was a primitive mechanical computer.
            and now in 2022, the world has developed nearly 9000 different programming languages for computers. Programmes are used a tremendous amount in most peoples lifetime. Think of how your
            alarm clock works in the morning, somebody had to program the different buttons and times there are on the clock.
        </p>
        <p>
            We have now implemented new tutorials to try and persuade and teach a small amount of programming to completely new begginners to the proggramming world. Your mind is your limit!
        </p>

        <div class="core-chapter-col">                                   <!--Chapter Column Start -->
            <div class="flexbox-container">                             <!--Chapter Left Start -->

                <div class="chapter-header">                            <!--Chapter Header Start -->
                    <a name="Chapter1"></a>
                    <div class="chapter-header-num">Chapter 1</div>
                    <div class="chapter-header-title">Core Programming Concepts</div>
                </div>                                                  <!--Chapter Header End -->

                <div class="core-chapter-list">                          <!--Chapter List Start -->
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.1</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_1.php">
                            Functions, Statements, and Syntax Errors
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.2</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_2.php">
                            Comments
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.3</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_3.php">
                            Introduction to Objects and Variables
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.4</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_4.php">
                            Variable Assignment and Initialization
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.5</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_5.php">
                            Inputting and Outputting
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.6</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_6.php">
                            Data Types
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.7</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_7.php">
                            Keywords and naming identifiers
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.8</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_8.php">
                            Whitespace and basic formatting
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.9</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_9.php">
                            Introduction to literals and operators
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.10</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_10.php">
                            Expressions
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.11</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_11.php">
                            For Loops
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.12</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_12.php">
                            Boolean
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.13</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_13.php">
                            IF Statements
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.14</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_14.php">
                            Why Functions are Useful
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.15</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_15.php">
                            More on Functions
                            </a>
                        </div>
                    </div>
                    <div class="lesson-row">
                        <div class="lesson-row-num">1.X</div>
                        <div class="lesson-row-title">
                            <a href="chapter1/1_X.php">
                            Basic Programming Summary and Quiz
                            </a>
                        </div>
                    </div>

                </div>      <!--Chapter List End -->
            </div>          <!--Chapter Left End -->
        </div>              <!--Chapter Column End -->
    </section>

    <script src="../js/showHide.js"></script>   
</body>

<?php require_once __DIR__ . '/../footer.phtml';?>

