<?php require_once __DIR__ . '/../base.phtml';?>
<?php require_once __DIR__ . '/nav.phtml';?>

<body>

    <div class="text-box">
        <h1>About CodeHeads</h1>
    </div>
    </section>

<!--------- Contact Page ------------------>
    <section class="about">
        <div class="row">

            <div class="left">
                <img src="img/programmer.png" alt="programmer-img">
            </div>

            <div class="right">
                <p>
                    CodeHeads is a place where you can learn programming languages with ease!<br><br>

                    Our programmers started out like anybody else and found that resources they learnt the most from started from the very
                    basics of the language and parts behind that. Resouces you will see on websites, will give you a breif introduction. But CodeHeads
                    wants you to make the most of your time and learn parts that are extremely useful with lots of background knowledge.<br><br>

                    Begin your adventure now and master your chosen language in no time!
                </p>

            </div>


        </div>
    </section>

</body>

<script src="/js/showHide.js"></script>

<?php require_once __DIR__ . '/footer.phtml';?>





