<?php require_once __DIR__ . '/../base.phtml';?>
<?php require_once __DIR__ . '/nav.phtml';?>
<body>
<!--------------------------------------- Head Section -------------------------------------->
    <div class="text-box">
        <h1>Choose Your Langauge</h1>
        <p>
            Learning a Programming Langauge is easy when you get taught the correct way!<br>
            Begin now and start your path to a new career!
        </p> 
        
    </div>
    </section>
    
<!--------------------------------------- Course Section -------------------------------------->
    <section class="course">
        <h2>Courses We Offer</h2>
        <p>
            All of the courses we offer are for new programmers who dont have any previous knowledge of coding<BR>
            So be ready to turn into a pro in no time!
        </p>

        <div class="row2">
                <div class="course-col">
                    <h3>C++</h3>
                    <p>
                        C++ is the extended version of the C Language. This object-oriented language offers a clearer understanding of Various
                        programs and helps develop high-performance applications that can be used on multiple platforms.<br><br>
                        <a href="cplus/cplusChapter.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
                <div class="course-col">
                    <h3>C Language</h3>
                    <p>
                        C is a powerful general-purpose programming language. It can be used to develop software like operating systems, databases, compilers,
                        and so on. C Programming is an excellent language to learn programming for begginers<br><br>
                        <a href="unavailable.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
                <div class="course-col">
                    <h3>HTML5</h3>
                    <p>
                       The HyperText Markup Language is the standard markup language for documents to be displayed in a web browser.
                       It can be assisted by other technoligies such as Cascading Style Sheets and Scripting Languages.<br><br>
                       <a href="unavailable.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
            </div>
    </section>


</body>
<script src="/js/showHide.js"></script>    
<?php require_once __DIR__ . '/footer.phtml';?>

