<?php require_once __DIR__ . '/../base.phtml';?>
<?php require_once __DIR__ . '/nav.phtml';?>
<body>

    <div class="text-box">
        <h1>Welcome to CodeHeads</h1>
        <p>
            <br>The Best platform to start your Career in Programming!<br>
            Learning a Programming Language is easy when you get taught the correct way!<br> Begin now and start your path to a New Career!
        </p>
        <a href="courses.php" class="hero-btn">Get Started!</a>
    </div>
    </section>

    <section class="inspiration">
        <h2>Why Start Programming?</h2>
        <p>
            The 21st Century is known for its accelerating technological developments. Wherever we look at, whatever we use has something to
            do with technology. Starting from the alarm clock on your mobile device that wakes us up, to the heater you can turn on and off with your mobile phone.
            Technology makes our lives easier no matter where you are located.<br><br>
            Behind all the technology we use and see - There is someone who programmed it to look/function the way it does.
        </p>
        <div class="row2">
                <div class="inspiration-col">
                    <img src="../../img/inspiration1.png">
                    <div class="layer">
                        <h3>Guaranteed Job</h3>
                    </div>
                    <p>
                        We currently live in a technology era, this growth is nowhere no its endmark, as we see every year a new phone with amazing
                        capibilities. Meaning there will always be a high demand for programmers. <br>Software jobs are growing everyday as businesses in your local area
                        are having there very own website developed.
                    </p>
                </div>
                <div class="inspiration-col">
                    <img src="../../img/inspiration2.png">
                    <div class="layer">
                        <h3>Work From Home!</h3>
                    </div>
                    <p>
                        Since the job only requires a computer and an internet connection, employees will have the opportunity to work from home if there employer allows them to. 
                        Ever since the recent Covid-19 pandemic hit the globe. Many people have been working from home, and saving the company and themselves a tonne of money.
                    </p>
                </div>
                <div class="inspiration-col">
                    <img src="../../img/inspiration3.png">
                    <div class="layer">
                        <h3>Be Your Own Boss</h3>
                    </div>
                    <p>
                        Becoming Self-Employed is the path many programmers eventually choose. Knowing how to code allows you to look into creating a business of your own<br>
                        This could be an online shop, Mobile Applications, Website Design Company, and even offering to tutor new/intermediate programmers!<br>
                    </p>
                </div>
            </div>

    </section>

    <section class="course">
        <h2>Courses We Offer</h2>
        <p>
            All of the courses we offer, are for new programmers who dont have any previous knowledge of coding.<BR>
            Start now and become a pro in no time!
        </p>

        <div class="row2">
                <div class="course-col">
                    <h3>C++</h3>
                    <p>
                        C++ is the extended version of the C Language. This object-oriented language offers a clearer understanding of Various
                        programs and helps develop high-performance applications that can be used on multiple platforms.<br><br>
                        <a href="cplus/cplusChapter.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
                <div class="course-col">
                    <h3>C Language</h3>
                    <p>
                        C is a powerful general-purpose programming language. It can be used to develop software like operating systems, databases, compilers,
                        and so on. C Programming is an excellent language to learn programming for begginers<br><br>
                        <a href="unavailable.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
                <div class="course-col">
                    <h3>HTML5</h3>
                    <p>
                       The HyperText Markup Language is the standard markup language for documents to be displayed in a web browser.
                       It can be assisted by other technoligies such as Cascading Style Sheets and Scripting Languages.<br><br>
                       <a href="unavailable.php">
                            <button type="submit" class="hero-btn">Get Started</button>
                        </a>
                    </p>
                </div>
            </div>
    </section>

    <section class="testimonials">
            <h2>Our Previous Users</h2>
            <p>CodeHeads has helped so many individuals learn how to program, here are some reviews from them.</p>

            <div class="row2">
                <div class="testimonials-col">
                    <div>
                        <h3>Christopher Adams</h3>
                        <p>
                            The tutorials are extremely detailed and taught in a way anybody can understand!
                        </p>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="far fa-star"></i>
                    </div>
                </div>

                <div class="testimonials-col">
                    <div>
                        
                        <h3>Jay Smith</h3>
                        
                        <p>
                            Learning C++ by CodeHeads has given me such a wide oppotunity in my life. I have now got a job at a HighTech Company designing
                            High-Performance Programs!
                        </p>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star-half-alt"></i>
                    </div>
                </div>
            </div>
        </section>

</body>
<script src="/js/showHide.js"></script>    
<?php require_once __DIR__ . '/footer.phtml';?>
