
    <body>
        <div class="bg-color"><!--bg color Start-->

            <section class="top-bar">
                <nav>
                    <div class="nav-links" id="navLinks">
                        <i class="fas fa-times" onclick="hideMenu()"></i>
                        <ul>
                            <li><a href="../index.html">HOME</a></li>
                            <li><a href="../about.html">ABOUT</a></li>
                            <li><a href="../course.html">COURSE</a></li>
                            <li><a href="../getStarted.html">GET STARTED</a></li>
                            <li><a href="../blog.html">BLOG</a></li>
                            <li><a href="../contact.html">CONTACT</a></li>
                        </ul>
                    </div>
                    <i class="fas fa-bars" onclick="showMenu()"></i>
                </nav>
            </section>
            <section class="lesson-content">

                <div class="lesson-container">
                    <div class="content">
                        <h1>Chapter 1.8 - Whitespace and Basic Formatting</h1>
                        <hr>

                        <div class="part-content">
                            <h2>Whitespace</h2>
                            <p>
                                Whitespace is a term that refers to characters that are used for formatting purposes. 
                                In C++, this refers primarily to spaces, tabs, and newlines. The C++ compiler generally ignores whitespace, 
                                with a few minor exceptions(when processing text literals). For this reason, we say that C++ is a whitespace-independent 
                                language.<br>Consequently, the following statements do the same thing:
                            </p>
                                <pre>
                                    <code class="language-cpp line-numbers">
                                        std::cout << "Hello World!";
                                        std::cout << "Hello World!";
                                        std::cout << "Hello World!";

                                        std::cout
                                            << "Hello World!";
                                       
                                    </code>
                                </pre>
                                

                        </div>
                        <div class="part-content">
                            <h2>Basic Formatting</h2>
                            <p>
                                Unlike some languages, C++ does not enforce any kind of formatting restrictions on the programmer 
                                (remember, trust the programmer!). Many different methods of formatting C++ programs have been developed 
                                throughout the years, and you will find disagreement on which are best. The best style are the ones that
                                produce the most readable code and provide the most consistency. 
                            </p>
                            <div class="lesson-practice">
                                <mark>Best Practice</mark> - Your lines should be no longer than 80 characters in length.
                            </div>
                        </div>
                        
                    </div>

                        <div class="prev-next">
                            <div class="prev-next-inline">
                                <a class="nav-link" href="chapter1_9.html">
                                    <div class="nav-button nav-button-next">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Next Lesson</div>
                                            <div class="nav-button-lesson">
                                                <span class="nav-button-lesson-number">1.9</span>
                                                Introduction to Literals and Operators
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <a class="nav-link" href="../cplusChapter.html">
                                    <div class="nav-button nav-button-index">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-home" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Back to Table of Contents</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="nav-link" href="chapter1_7.html">
                                    <div class="nav-button nav-button-prev">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Previous Lesson</div>
                                            <div class="nav-button-lesson">
                                                <span class="nav-button-lesson-number">1.7</span>
                                                Keywords and Naming Identifiers
                                            </div>
                                        </div>
                                    </div>
                                </a>

                            </div>
                        </div>
                </div>


         </div>
                
            </section>
    
            <!-- Footer -->
            <section class="footer">
                <h4>About Us</h4>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
                <div class="icons">
                    <i class="fab fa-facebook-square"></i>
                    <i class="fab fa-twitter-square"></i>
                    <i class="fab fa-instagram-square"></i>
                    <i class="fab fa-linkedin"></i>
                </div>
                <p>
                    Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
                </p>
            </section>

         </div> <!--bg color End -->
        


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>
     <script>
        function show_hide(element)
        {
           var myAnswer = element.nextElementSibling;

           var displaySetting = myAnswer.style.display;

           var quizButton = element;

           if(displaySetting=="inline-block"){
               myAnswer.style.display = 'none';

               quizButton.innerHTML = 'Show Solution';
           }
           else
           {
               myAnswer.style.display = 'inline-block';
               quizButton.innerHTML = 'Hide Solution';
           }
        }
    </script>
    </body>
