
    <body>
        <div class="bg-color"><!--bg color Start-->

            <section class="top-bar">
                <nav>
                    <div class="nav-links" id="navLinks">
                        <i class="fas fa-times" onclick="hideMenu()"></i>
                        <ul>
                            <li><a href="../index.html">HOME</a></li>
                            <li><a href="../about.html">ABOUT</a></li>
                            <li><a href="../course.html">COURSE</a></li>
                            <li><a href="../getStarted.html">GET STARTED</a></li>
                            <li><a href="../blog.html">BLOG</a></li>
                            <li><a href="../contact.html">CONTACT</a></li>
                        </ul>
                    </div>
                    <i class="fas fa-bars" onclick="showMenu()"></i>
                </nav>
            </section>
            <section class="lesson-content">

                <div class="lesson-container">
                    <div class="content">
                        <h1>Chapter 1.6 -Uninitialized Variables and Undefined Behaviour</h1>
                        <hr>

                        <div class="part-content">
                            <h2>Uninitialized Variables</h2>
                            <p>
                                Unlike some programming languages, C++ does not initialize most variables to a given value automatically. 
                                Thus, when a variable is assigned a memory location by the compiler, the default value of that variable is 
                                whatever (garbage) value happens to already be in that memory location. A variable that has not been given 
                                a known value is called an <b>uninitialized variable</b>.
                            </p>
                        </div>
                        <div class="part-content">
                            <h2>Undefined Behaviour</h2>
                            <p>
                                Using the value from an uninitialized variable is our first example of undefined behavior. 
                                <b>Undefined Behavior</b>  is the result of executing code whose behavior is not well defined by the C++ Language. 
                                In this case, the C++ language does not have any rules determining what happens if you use the value of a 
                                variable that has not been given a known value. Consequently, if you do this, undefined behavior will result.
                            </p>
                            <p>
                                Code implementing undefined behavior may exhibit any of the following symptoms:
                                <ul>
                                    <li>Your program produces a different result every time it is run.</li>
                                    <li>Your program consistently produces the same incorrect result.</li>
                                    <li>Your program behaves inconsistently.</li>
                                    <li>Your program seems like j working but produces incorrect results later in the program. </li>
                                    <li>Your program crashes, either immediately or later.</li>
                                    <li>Your program works on some compilers but not others.</li>
                                    <li>Your program works until you change some other seemingly unrelated code.</li>
                                </ul> 
                            </p>
                            <p>
                                C++ contains mant cases that can result in undefined behavior, such as using unititialized variables.
                            </p>
                        </div>

                        <div class="part-content quiz">

                            <h2>Chapter 1.6 End of Topic Quiz</h2>
                            <p>
                                The following quiz is meant to reinforce your understanding of the material presented above.
                            </p>
<!-- --------------------------------------------------Question 1 Start --------------------------------------------------------------------------------- -->
                                <h4 class="quiz-question">1. What is an uninitialized variable? Why should you avoid using them?</h4>
                                <button onclick="show_hide(this)" class="quiz-button">Show Solution</button>
                                <p id="answer">
                                    An <b>uninitialized</b> variable is a variable that has not been given a value by the program. 
                                    Using the value stored in uninitialized variable will result in undefined behavior.
                                </p>
                                <br><br><hr>

<!-- ------------------------------------------------Question 2 Start --------------------------------------------------------------------------------- -->
                                <h4 class="quiz-question">2. What is undefined behavior, and what can happen if you do something that exhibits undefined behavior?</h4>
                                <button onclick="show_hide(this)" class="quiz-button">Show Solution</button>
                                <p id="answer">
                                    <b>Undefined behavior</b> is the result of executing code whose behavior is not well defined by the language. 
                                    The result can be almost anything, including something that behaves correctly.
                                </p>
                                <br><br><hr>

                        </div>
                        
 
                    </div>

                        <div class="prev-next">
                            <div class="prev-next-inline">
                                <a class="nav-link" href="chapter1_7.html">
                                    <div class="nav-button nav-button-next">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-chevron-circle-right" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Next Lesson</div>
                                            <div class="nav-button-lesson">
                                                <span class="nav-button-lesson-number">1.6</span>
                                                Keywords and Naming Identifiers
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <a class="nav-link" href="../cplusChapter.html">
                                    <div class="nav-button nav-button-index">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-home" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Back to Table of Contents</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="nav-link" href="chapter1_5.html">
                                    <div class="nav-button nav-button-prev">
                                        <div class="nav-button-icon">
                                            <i class="fas fa-chevron-circle-left" aria-hidden="true"></i>
                                        </div>
                                        <div class="nav-button-text">
                                            <div class="nav-button-title">Previous Lesson</div>
                                            <div class="nav-button-lesson">
                                                <span class="nav-button-lesson-number">1.5</span>
                                                Uninitialized Variables and Undefined Behaviour
                                            </div>
                                        </div>
                                    </div>
                                </a>

                            </div>
                        </div>
                </div>


         </div>
                
            </section>
    
            <!-- Footer -->
            <section class="footer">
                <h4>About Us</h4>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
                <div class="icons">
                    <i class="fab fa-facebook-square"></i>
                    <i class="fab fa-twitter-square"></i>
                    <i class="fab fa-instagram-square"></i>
                    <i class="fab fa-linkedin"></i>
                </div>
                <p>
                    Made with <i class="fab fa-facebook-square"></i> Easy Tutorials
                </p>
            </section>

         </div> <!--bg color End -->
        


     <script>
        var navLinks = document.getElementById("navLinks")

        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
     </script>
     <script>
        function show_hide(element)
        {
           var myAnswer = element.nextElementSibling;

           var displaySetting = myAnswer.style.display;

           var quizButton = element;

           if(displaySetting=="inline-block"){
               myAnswer.style.display = 'none';

               quizButton.innerHTML = 'Show Solution';
           }
           else
           {
               myAnswer.style.display = 'inline-block';
               quizButton.innerHTML = 'Hide Solution';
           }
        }
    </script>
    </body>
